/* UI and Canvas adapter. Input images never leave the browser. */
(function(){
  'use strict';
  const C=PanelCore, A=PanelAI, $=id=>document.getElementById(id);
  const ai={worker:null,pending:null,cache:new Map(),revision:0,cancelled:false,pixels:0,compareToken:0};
  const state={image:null,width:0,height:0,source:'',rects:[],selected:-1,tool:'select',history:[],drag:null,busy:false,loading:false,loadToken:0};
  const stage=$('stage'), canvas=$('canvas'), ctx=canvas.getContext('2d');
  const buttonIDs=['detect','grid','drawTool','selectTool','loadTemplate','saveTemplate','all','export'];
  function message(text,type=''){ $('message').textContent=text; $('message').className=`notice ${type}`; }
  function guarded(fn){return async(...args)=>{if(state.busy)return;try{await fn(...args);}catch(error){message(error.message || '処理に失敗しました。','error');if($('mode').value==='ai')$('aiStatus').textContent=error.message || '処理に失敗しました。';}};}
  function bind(id,event,fn){$(id).addEventListener(event,guarded(fn));}
  function snapshot(){state.history.push(JSON.stringify({rects:state.rects,selected:state.selected}));if(state.history.length>30)state.history.shift();$('undo').disabled=false;}
  function settings(){return {edge:Number($('edge').value),square:$('square').checked,originals:$('originals').checked,trigger:$('trigger').value.trim(),mode:$('mode').value,factor:Number($('factor').value),provider:$('provider').value};}
  function names(){return C.PRESETS[$('preset').value].names;}
  function options(){return {rows:Number($('rows').value),cols:Number($('cols').value),color:$('color').value,tolerance:Number($('tolerance').value),coverage:Number($('coverage').value)/100,inset:Number($('inset').value),names:names()};}
  function makeCanvas(w,h){const c=document.createElement('canvas');c.width=w;c.height=h;return c;}
  function crop(r){const b=C.pixelBox(r,state.width,state.height),c=makeCanvas(b.w,b.h);c.getContext('2d').drawImage(state.image,b.x,b.y,b.w,b.h,0,0,b.w,b.h);return c;}
  function resized(r,config){const b=C.pixelBox(r,state.width,state.height),s=C.outputSize(b.w,b.h,config.edge,config.square),c=makeCanvas(s.width,s.height),g=c.getContext('2d');
    if(config.square){g.fillStyle='#fffefa';g.fillRect(0,0,c.width,c.height);}g.imageSmoothingEnabled=true;g.imageSmoothingQuality='high';g.drawImage(state.image,b.x,b.y,b.w,b.h,(s.width-s.drawWidth)/2,(s.height-s.drawHeight)/2,s.drawWidth,s.drawHeight);return {canvas:c,size:s,box:b};}
  function blob(c){return new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('PNGへの変換に失敗しました。')),'image/png'));}
  function download(content,name){const url=URL.createObjectURL(content),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
  function textBlob(text){return new Blob([text],{type:'application/json;charset=utf-8'});}
  function setTool(tool){state.tool=tool;for(const [id,t] of [['selectTool','select'],['drawTool','draw']]){$(id).classList.toggle('active',tool===t);$(id).setAttribute('aria-pressed',String(tool===t));}$('canvasHint').textContent=tool==='draw'?'画像上をドラッグして新しい枠を追加':'枠をドラッグして移動 · 角でサイズ変更 · 矢印キーで微調整';}
  function updateCounts(){const count=state.rects.length,selected=state.rects.filter(r=>r.enabled).length;
    $('panelCount').textContent=count;$('previewCount').textContent=count;$('selectedCount').textContent=`${selected}枚`;
    buttonIDs.forEach(id=>$(id).disabled=state.loading || !state.image || ((id==='export'||id==='saveTemplate'||id==='all')&&!count));$('export').disabled=state.loading || !selected || !state.image;$('undo').disabled=!state.history.length;$('all').textContent=count && selected===count?'すべて解除':'すべて選択';updateAIControls();}
  function draw(){if(!state.image)return;
    const bounds=stage.getBoundingClientRect(),scale=Math.min((bounds.width-34)/state.width,(bounds.height-34)/state.height),w=Math.max(1,Math.round(state.width*scale)),h=Math.max(1,Math.round(state.height*scale)),dpr=Math.min(devicePixelRatio||1,2);
    canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);canvas.style.width=`${w}px`;canvas.style.height=`${h}px`;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.drawImage(state.image,0,0,w,h);
    if(!$('showBoxes').checked)return;
    state.rects.forEach((r,i)=>{const x=r.x*w,y=r.y*h,rw=r.w*w,rh=r.h*h,active=i===state.selected;ctx.strokeStyle=active?'#e99e40':r.enabled?'#1c8275':'#8a9290';ctx.lineWidth=active?2.5:1.3;ctx.setLineDash(r.enabled?[]:[4,3]);ctx.fillStyle=active?'#e99e401b':'#1c827507';ctx.fillRect(x,y,rw,rh);ctx.strokeRect(x,y,rw,rh);ctx.setLineDash([]);ctx.font='bold 10px Segoe UI';const label=String(i+1).padStart(2,'0');ctx.fillStyle=active?'#e99e40':'#265b53';ctx.fillRect(x,y,23,16);ctx.fillStyle='#fff';ctx.fillText(label,x+4,y+11);if(active){ctx.fillStyle='#fff';for(const [cx,cy] of [[x,y],[x+rw,y],[x,y+rh],[x+rw,y+rh]]){ctx.fillRect(cx-3,cy-3,6,6);ctx.strokeRect(cx-3,cy-3,6,6);}}});
  }
  function detail(){const r=state.rects[state.selected];$('detail').hidden=!r;if(!r){updateAIControls();showComparison();return;}const b=C.pixelBox(r,state.width,state.height);$('name').value=r.name;$('caption').value=r.caption;for(const [id,key]of[['rx','x'],['ry','y'],['rw','w'],['rh','h']])$(id).value=b[key];const config=settings();let s;try{s=outputSize(r,config);}catch(e){$('outputInfo').textContent=e.message;updateAIControls();showComparison();return;}$('outputInfo').textContent=`原寸 ${b.w} × ${b.h} → 出力 ${s.width} × ${s.height}px${s.scale>1?` · ${s.scale.toFixed(1)}倍拡大`:''}${config.mode==='ai'?' · AI':''}`;updateAIControls();showComparison();}
  function select(index){state.selected=index;draw();detail();document.querySelectorAll('.panel-row,.preview-card').forEach(el=>el.classList.toggle('active',Number(el.dataset.index)===index));}
  function render(){updateCounts();draw();detail();const list=$('panels'),previews=$('previews');list.replaceChildren();previews.replaceChildren();
    if(!state.rects.length){const p=document.createElement('p');p.className='muted compact';p.textContent='分割または手動で枠を追加してください。';list.append(p);const q=document.createElement('p');q.className='muted preview-empty';q.textContent='作成した枠のプレビューがここに並びます。';previews.append(q);return;}
    state.rects.forEach((r,i)=>{const b=C.pixelBox(r,state.width,state.height),row=document.createElement('div');row.className='panel-row'+(i===state.selected?' active':'');row.dataset.index=i;const check=document.createElement('input');check.type='checkbox';check.checked=r.enabled;check.setAttribute('aria-label',`${r.name || `パネル${i+1}`}を書き出す`);check.addEventListener('change',()=>{if(state.busy)return;snapshot();r.enabled=check.checked;render();});const index=document.createElement('span');index.className='index';index.textContent=String(i+1).padStart(2,'0');const btn=document.createElement('button');btn.textContent=r.name || `panel_${i+1}`;btn.title=`${r.name} · ${b.w} × ${b.h}px`;btn.addEventListener('click',()=>select(i));row.append(check,index,btn);list.append(row);
      const card=document.createElement('button');card.className='preview-card'+(i===state.selected?' active':'')+(!r.enabled?' excluded':'');card.dataset.index=i;card.setAttribute('aria-label',`プレビュー ${r.name}`);const c=makeCanvas(180,180),g=c.getContext('2d'),scale=Math.min(180/b.w,180/b.h);g.fillStyle='#f2f1eb';g.fillRect(0,0,180,180);g.drawImage(state.image,b.x,b.y,b.w,b.h,(180-b.w*scale)/2,(180-b.h*scale)/2,b.w*scale,b.h*scale);const n=document.createElement('strong');n.textContent=r.name || `panel_${i+1}`;const s=document.createElement('small');s.textContent=`${b.w} × ${b.h} px${ai.cache.has(aiKey(r,settings()))?' · AI済':''}`;card.append(c,n,s);card.addEventListener('click',()=>select(i));previews.append(card);
    });
  }
  async function loadImage(url,name,kind,rects=[]){const token=++state.loadToken;state.loading=true;updateCounts();const image=new Image();try{await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(new Error('画像を開けません。PNG / JPEG / WebPを選んでください。'));image.src=url;});if(token!==state.loadToken)return false;
    const width=image.naturalWidth,height=image.naturalHeight;if(width>8192 || height>8192 || width*height>36000000)throw new Error('画像が大きすぎます。各辺8192px以下、合計3600万画素以下にしてください。');
    clearAI();state.image=image;state.width=width;state.height=height;state.source=name;state.rects=rects;state.selected=rects.length?0:-1;state.history=[];state.drag=null;state.loading=false;$('empty').hidden=true;canvas.hidden=false;$('sourceTitle').textContent=name;$('dimensions').textContent=`${width} × ${height} px`;$('sourceKind').textContent=kind;setTool('select');render();return true;}finally{if(token===state.loadToken){state.loading=false;updateCounts();}}}
  async function openFile(file){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('PNG / JPEG / WebPの画像を選んでください。');if(file.size>35*1024*1024)throw new Error('画像は35MB以下にしてください。');const url=URL.createObjectURL(file);try{if(await loadImage(url,file.name,'読み込んだ画像'))message('画像を読み込みました。行数・列数を指定して分割するか、手動で枠を追加してください。');}finally{URL.revokeObjectURL(url);}}
  async function sample(){await loadImage(PanelSample.url,'キャラクター資料サンプル','手動定義の参考枠',PanelSample.rects());message('添付画像に手動で定義した参考枠を適用しました。文字とカラーパレットを除外し、Chibiは書き出し対象から外しています。切れや余白をプレビューで確認してください。');}
  async function demo(){const c=makeCanvas(1536,1024),g=c.getContext('2d');g.fillStyle='#fffefa';g.fillRect(0,0,c.width,c.height);const colors=['#c4dfd3','#eacfb6','#c6d8e3','#e4c8cb','#d2d8bd','#e0d2e5'];
    for(let r=0;r<2;r++)for(let x=0;x<3;x++){const cx=x*512+256,cy=r*512+250;g.fillStyle=colors[r*3+x];g.fillRect(x*512+40,r*512+40,432,432);g.fillStyle='#fffefa';g.beginPath();g.arc(cx,cy-20,105,0,Math.PI*2);g.fill();g.fillStyle='#41695e';g.font='bold 90px Segoe UI';g.textAlign='center';g.fillText(String(r*3+x+1).padStart(2,'0'),cx,cy+10);g.font='24px Segoe UI';g.fillText('DETECTION TEST',cx,cy+157);}
    g.strokeStyle='#ff00ff';g.lineWidth=10;for(const x of[5,512,1024,1531]){g.beginPath();g.moveTo(x,0);g.lineTo(x,1024);g.stroke();}for(const y of[5,512,1019]){g.beginPath();g.moveTo(0,y);g.lineTo(1536,y);g.stroke();}
    $('preset').value='expressions';applyPreset();$('color').value='#ff00ff';$('tolerance').value=80;$('coverage').value=70;$('inset').value=4;sliderLabels();await loadImage(c.toDataURL(),'枠検出デモ · 2 × 3','合成テスト画像');message('自動分割を試すための合成テスト画像です。「枠線から自動分割」を押してください。キャラクター素材ではありません。');}
  function applyPreset(){const p=C.PRESETS[$('preset').value];$('rows').value=p.rows;$('cols').value=p.cols;}
  function sliderLabels(){$('tolValue').textContent=$('tolerance').value;$('coverageValue').textContent=$('coverage').value+'%';}
  function replaceRects(rects){snapshot();state.rects=rects;state.selected=rects.length?0:-1;setTool('select');render();}
  function normalizedPoint(e){const b=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(1,(e.clientX-b.left)/b.width)),y:Math.max(0,Math.min(1,(e.clientY-b.top)/b.height))};}
  function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
  canvas.addEventListener('pointerdown',e=>{if(state.busy || !state.image || !$('showBoxes').checked || e.button!==0)return;canvas.focus();const p=normalizedPoint(e),bounds=canvas.getBoundingClientRect(),r=state.rects[state.selected];let corner='';
    if(state.tool==='select' && r){for(const [name,x,y] of[['tl',r.x,r.y],['tr',r.x+r.w,r.y],['bl',r.x,r.y+r.h],['br',r.x+r.w,r.y+r.h]])if(Math.abs(p.x-x)*bounds.width<9 && Math.abs(p.y-y)*bounds.height<9){corner=name;break;}}
    if(state.tool==='draw'){if(state.rects.length>=80){message('枠は最大80個です。','error');return;}state.drag={mode:'draw',start:p,end:p};}
    else {let hit=corner?state.selected:-1;if(hit<0)for(let i=state.rects.length-1;i>=0;i--){const t=state.rects[i];if(p.x>=t.x && p.x<=t.x+t.w && p.y>=t.y && p.y<=t.y+t.h){hit=i;break;}}if(hit<0){select(-1);return;}select(hit);state.drag={mode:corner?'resize':'move',corner,start:p,original:{...state.rects[hit]},index:hit,saved:false};}
    canvas.setPointerCapture(e.pointerId);e.preventDefault();});
  canvas.addEventListener('pointermove',e=>{const d=state.drag;if(!d)return;const p=normalizedPoint(e);if(d.mode==='draw'){d.end=p;draw();const b=canvas.getBoundingClientRect();ctx.save();ctx.setTransform(canvas.width/b.width,0,0,canvas.height/b.height,0,0);ctx.strokeStyle='#e99e40';ctx.lineWidth=2;ctx.setLineDash([5,4]);ctx.strokeRect(Math.min(d.start.x,p.x)*b.width,Math.min(d.start.y,p.y)*b.height,Math.abs(p.x-d.start.x)*b.width,Math.abs(p.y-d.start.y)*b.height);ctx.restore();return;}
    if(Math.abs(p.x-d.start.x)*state.width+Math.abs(p.y-d.start.y)*state.height<1)return;
    if(!d.saved){snapshot();d.saved=true;}const r=state.rects[d.index],o=d.original,dx=p.x-d.start.x,dy=p.y-d.start.y;
    if(d.mode==='move'){r.x=clamp(o.x+dx,0,1-o.w);r.y=clamp(o.y+dy,0,1-o.h);}else{let left=o.x,right=o.x+o.w,top=o.y,bottom=o.y+o.h;const minW=Math.min(8/state.width,o.w),minH=Math.min(8/state.height,o.h);if(d.corner.includes('l'))left=clamp(p.x,0,right-minW);else right=clamp(p.x,left+minW,1);if(d.corner.includes('t'))top=clamp(p.y,0,bottom-minH);else bottom=clamp(p.y,top+minH,1);r.x=left;r.y=top;r.w=right-left;r.h=bottom-top;}draw();detail();});
  function endDrag(cancel=false){const d=state.drag;if(!d)return;state.drag=null;if(cancel){if(d.saved)state.rects[d.index]=d.original;render();return;}
    if(d.mode==='draw'){const x=Math.min(d.start.x,d.end.x),y=Math.min(d.start.y,d.end.y),w=Math.abs(d.end.x-d.start.x),h=Math.abs(d.end.y-d.start.y);if(w*state.width>=8 && h*state.height>=8){snapshot();state.rects.push(C.makeRect(x,y,w,h,`panel_${String(state.rects.length+1).padStart(2,'0')}`));state.selected=state.rects.length-1;setTool('select');}else message('枠は幅・高さともに8px以上になるように描いてください。','error');}render();}
  canvas.addEventListener('pointerup',()=>endDrag());canvas.addEventListener('pointercancel',()=>endDrag(true));canvas.addEventListener('lostpointercapture',()=>endDrag());
  canvas.addEventListener('keydown',e=>{if(state.busy)return;if(e.key==='Escape'){endDrag(true);setTool('select');return;}const r=state.rects[state.selected];if(!r)return;const direction={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(direction){e.preventDefault();snapshot();const step=e.shiftKey?10:1;r.x=clamp(r.x+direction[0]*step/state.width,0,1-r.w);r.y=clamp(r.y+direction[1]*step/state.height,0,1-r.h);render();}});
  bind('open','click',()=>$('file').click());bind('file','change',async()=>{const file=$('file').files[0];$('file').value='';await openFile(file);});bind('sample','click',sample);bind('emptyDemo','click',sample);bind('demo','click',demo);
  stage.addEventListener('dragover',e=>{e.preventDefault();stage.classList.add('dragover');});stage.addEventListener('dragleave',()=>stage.classList.remove('dragover'));stage.addEventListener('drop',guarded(async e=>{e.preventDefault();stage.classList.remove('dragover');await openFile(e.dataTransfer.files[0]);}));
  bind('preset','change',applyPreset);for(const id of['tolerance','coverage'])bind(id,'input',sliderLabels);
  bind('grid','click',()=>{const o=options(),rects=C.grid(state.width,state.height,o.rows,o.cols,o.inset,o.names);replaceRects(rects);message(`${rects.length}個の枠を均等配置しました。配置ずれや被写体の切れを確認してください。`);});
  bind('detect','click',async()=>{message('枠線を検出しています…');await new Promise(resolve=>setTimeout(resolve,20));const c=makeCanvas(state.width,state.height),g=c.getContext('2d',{willReadFrequently:true});g.drawImage(state.image,0,0);const result=C.detect(g.getImageData(0,0,c.width,c.height).data,c.width,c.height,options());replaceRects(result.rects);message(`縦 ${result.vertical.length}本・横 ${result.horizontal.length}本の枠線を検出し、${result.rects.length}枚に分割しました。プレビューを確認してください。`,'success');});
  bind('selectTool','click',()=>setTool('select'));bind('drawTool','click',()=>{$('showBoxes').checked=true;draw();setTool('draw');});bind('showBoxes','change',draw);
  bind('undo','click',()=>{const previous=state.history.pop();if(previous){const v=JSON.parse(previous);state.rects=v.rects;state.selected=v.selected;render();message('ひとつ前の枠設定に戻しました。');}});
  bind('all','click',()=>{snapshot();const enabled=!state.rects.every(r=>r.enabled);state.rects.forEach(r=>r.enabled=enabled);render();});
  bind('name','change',()=>{const r=state.rects[state.selected];if(r){snapshot();r.name=$('name').value.trim() || `panel_${state.selected+1}`;render();}});bind('caption','change',()=>{const r=state.rects[state.selected];if(r){snapshot();r.caption=$('caption').value.trim();}});
  bind('applyRect','click',()=>{const r=state.rects[state.selected];if(!r)return;const x=Number($('rx').value),y=Number($('ry').value),w=Number($('rw').value),h=Number($('rh').value);[x,y,w,h].forEach(n=>{if(!Number.isInteger(n))throw new Error('座標・寸法は整数で指定してください。');});const next=C.validRect({...r,x:x/state.width,y:y/state.height,w:w/state.width,h:h/state.height});C.pixelBox(next,state.width,state.height);snapshot();state.rects[state.selected]=next;render();message('切り出し範囲を更新しました。');});
  bind('remove','click',()=>{if(state.selected<0)return;snapshot();state.rects.splice(state.selected,1);state.selected=Math.min(state.selected,state.rects.length-1);render();});for(const id of['edge','square','originals','mode','factor','provider'])bind(id,'change',()=>{updateAIControls();detail();});
  bind('single','click',async()=>{const i=state.selected,r=state.rects[i];if(!r)return;const config=settings();beginBusy();try{let content;if(config.mode==='ai'){await processAI([{r,i}],config);content=ai.cache.get(aiKey(r,config)).blob;}else content=await blob(resized(r,config).canvas);checkCancelled();download(content,`${C.filename(r.name,i)}${config.mode==='ai'?'_ai':''}.png`);message('選択したパネルのPNGを保存しました。','success');}finally{endBusy();}});
  bind('saveTemplate','click',()=>{const t=C.template(state.rects,{width:state.width,height:state.height},settings());download(textBlob(JSON.stringify(t,null,2)),'panel-template.json');message('正規化座標と出力設定をJSONに保存しました。');});bind('loadTemplate','click',()=>$('templateFile').click());
  bind('templateFile','change',async()=>{const file=$('templateFile').files[0];$('templateFile').value='';if(!file)return;if(file.size>1024*1024)throw new Error('テンプレートは1MB以下にしてください。');let parsed;try{parsed=JSON.parse(await file.text());}catch{throw new Error('JSONファイルを読み取れません。');}const t=C.readTemplate(parsed);t.rects.forEach(r=>C.pixelBox(r,state.width,state.height));snapshot();state.rects=t.rects;state.selected=0;$('edge').value=t.settings.edge;$('square').checked=t.settings.square;$('originals').checked=t.settings.originals;$('trigger').value=t.settings.trigger;$('mode').value=t.settings.mode;$('factor').value=t.settings.factor;$('provider').value=t.settings.provider;render();const mismatch=Math.abs((t.source.width/t.source.height)/(state.width/state.height)-1)>0.01;message(mismatch?'元画像と縦横比が異なります。正規化座標で配置しましたが、すべての枠を確認・修正してください。':'テンプレートを適用しました。同じ縦横比でも配置は変わるため、切り出しを確認してください。',mismatch?'error':'');});
  async function exportZIP(){const enabled=state.rects.map((r,i)=>({r:{...r},i})).filter(({r})=>r.enabled),config=settings();if(!enabled.length)throw new Error('書き出すパネルを選んでください。');let totalPixels=0;for(const {r}of enabled){const b=C.pixelBox(r,state.width,state.height),s=outputSize(r,config);totalPixels+=s.width*s.height+(config.originals?b.w*b.h:0);}if(totalPixels>160000000)throw new Error('一度の出力が大きすぎます。長辺を小さくするか、パネルを分けて保存してください（合計1.6億画素まで）。');
    beginBusy();const entries=[],manifest={format:'lora-panel-studio-export',appVersion:C.VERSION,source:{name:state.source,width:state.width,height:state.height},resize:config.mode==='ai'?'Real-ESRGAN animevideov3 ONNX; native 4x, optional downsample to 2x':'browser-canvas-high-quality; no AI enhancement',settings:config,contactSheet:'original crops overview',panels:[]};
    const tile=200,gap=12,columns=Math.min(5,enabled.length),sheet=makeCanvas(columns*(tile+gap)+gap,Math.ceil(enabled.length/columns)*(tile+40+gap)+gap),sg=sheet.getContext('2d');sg.fillStyle='#f5f4ee';sg.fillRect(0,0,sheet.width,sheet.height);
    try{if(config.mode==='ai')await processAI(enabled,config);for(let k=0;k<enabled.length;k++){checkCancelled();const {r,i}=enabled[k],base=C.filename(r.name,i),cached=config.mode==='ai'?ai.cache.get(aiKey(r,config)):null,out=cached?{box:C.pixelBox(r,state.width,state.height),size:cached.size}:resized(r,config);message(`PNGを作成中… ${k+1} / ${enabled.length}`);$('export').textContent=`保存準備 ${k+1} / ${enabled.length}`;entries.push({name:`resized/${base}.png`,data:cached?cached.blob:await blob(out.canvas)});if(config.originals)entries.push({name:`originals/${base}.png`,data:await blob(crop(r))});const caption=[config.trigger,r.caption].filter(Boolean).join(', ');if(caption)entries.push({name:`resized/${base}.txt`,data:new TextEncoder().encode(caption+'\n')});manifest.panels.push({filename:`resized/${base}.png`,name:r.name,caption,normalized:{x:r.x,y:r.y,w:r.w,h:r.h},crop:out.box,output:{width:out.size.width,height:out.size.height,scale:out.size.scale},processing:cached?{engine:'onnxruntime-web',runtime:'1.23.2',model:cached.model,sha256:A.MODEL.sha256,provider:cached.provider,nativeScale:4,requestedScale:config.factor}: {engine:'browser-canvas'}});
      const x=gap+(k%columns)*(tile+gap),y=gap+Math.floor(k/columns)*(tile+40+gap),scale=Math.min(tile/out.box.w,tile/out.box.h);sg.fillStyle='#fffefa';sg.fillRect(x,y,tile,tile);sg.drawImage(state.image,out.box.x,out.box.y,out.box.w,out.box.h,x+(tile-out.box.w*scale)/2,y+(tile-out.box.h*scale)/2,out.box.w*scale,out.box.h*scale);sg.fillStyle='#243c3b';sg.font='12px Segoe UI';sg.fillText(base.slice(0,27),x,y+tile+18);sg.fillStyle='#7c8580';sg.font='10px Segoe UI';sg.fillText(`${out.box.w}×${out.box.h} → ${out.size.width}×${out.size.height}`,x,y+tile+32);await new Promise(resolve=>setTimeout(resolve,0));}
      entries.push({name:'contact-sheet.png',data:await blob(sheet)},{name:'manifest.json',data:new TextEncoder().encode(JSON.stringify(manifest,null,2))},{name:'panel-template.json',data:new TextEncoder().encode(JSON.stringify(C.template(state.rects,{width:state.width,height:state.height},config),null,2))});checkCancelled();message('ZIPをまとめています…');const zip=await PanelZip.pack(entries);checkCancelled();download(zip,'lora-panels.zip');message(`${enabled.length}枚を書き出しました。原寸${config.originals?'・拡大版':'保存なし、拡大版'}・確認一覧・設定JSONをZIPに保存しました。`,'success');
    }finally{endBusy();$('export').textContent='↓ ZIPで一括保存';}
  }
    function outputSize(r,config){const b=C.pixelBox(r,state.width,state.height);return config.mode==='ai'?A.size(b.w,b.h,config.factor,config.square):C.outputSize(b.w,b.h,config.edge,config.square);}
  function aiKey(r,config){const b=C.pixelBox(r,state.width,state.height);return [ai.revision,b.x,b.y,b.w,b.h,A.MODEL.id,config.factor,config.square,config.provider].join(':');}
  function clearAI(){ai.revision++;ai.cache.clear();ai.pixels=0;ai.compareToken++;$('comparison').hidden=true;$('comparisonEmpty').hidden=false;$('aiStatus').textContent='まず1枚で、線や顔の変化を確認してください。画像は送信しません。';}
  function updateAIControls(){const config=settings(),r=state.rects[state.selected];$('aiSettings').hidden=config.mode!=='ai';$('edgeLabel').hidden=config.mode==='ai';$('resizeHelp').textContent=config.mode==='ai'?'原寸の切り出しをAIで拡大します。ZIP保存時に未処理の対象も順番に処理します。':'縦横比を保った通常リサイズです。';$('aiOne').disabled=state.loading||state.busy||!r;$('aiBatch').disabled=state.loading||state.busy||!state.rects.some(r=>r.enabled);$('aiStop').disabled=!state.busy;}
  function beginBusy(){state.busy=true;ai.cancelled=false;document.body.classList.add('busy');$('aiProgress').hidden=false;$('aiProgress').value=0;updateAIControls();}
  function endBusy(){state.busy=false;document.body.classList.remove('busy');$('aiProgress').hidden=true;updateCounts();detail();}
  function checkCancelled(){if(ai.cancelled)throw new Error('処理を停止しました。完了済みのAI画像は保持しています。');}
  function workerRun(r,config,onProgress){
    if(!isSecureContext||location.protocol==='file:')throw new Error('AI拡大はHTTPSまたはlocalhostで開いてください。起動.cmdでHTTPプレビューを開けます。');
    if(!window.Worker||!window.OffscreenCanvas)throw new Error('このブラウザはAI処理に対応していません。新しいChrome / Edgeを利用してください。');
    if(!ai.worker)ai.worker=new Worker('./src/ai-worker.js');
    const c=crop(r),pixels=c.getContext('2d',{willReadFrequently:true}).getImageData(0,0,c.width,c.height).data;
    return new Promise((resolve,reject)=>{let timer;const finish=(error,value)=>{clearTimeout(timer);ai.pending=null;if(error){ai.worker?.terminate();ai.worker=null;reject(error);}else resolve(value);};
      const reset=()=>{clearTimeout(timer);timer=setTimeout(()=>finish(new Error('AI処理が時間内に応答しませんでした。CPUへの切り替え、または小さい枠で再試行してください。')),180000);};
      ai.pending={reject:()=>finish(new Error('処理を停止しました。完了済みのAI画像は保持しています。'))};
      ai.worker.onmessage=({data})=>{reset();if(data.type==='progress')onProgress(data);else if(data.type==='provider'){$('engineBadge').textContent=data.provider==='webgpu'?'GPU · WebGPU':'CPU · WASM';if(data.note)$('aiStatus').textContent=data.note;}else if(data.type==='complete')finish(null,data);else if(data.type==='error')finish(new Error(data.text));};
      ai.worker.onerror=()=>finish(new Error('AIエンジンを読み込めません。vendor / models / srcを含むフォルダーをHTTPで開いてください。'));
      reset();ai.worker.postMessage({pixels:pixels.buffer,width:c.width,height:c.height,factor:config.factor,square:config.square,provider:config.provider},[pixels.buffer]);
    });
  }
  async function processAI(items,config,continueOnError=false){
    // Reject before any inference when retaining all results would exceed the batch limit.
    const keys=new Set(),added=items.reduce((sum,{r})=>{const key=aiKey(r,config),s=outputSize(r,config);if(ai.cache.has(key)||keys.has(key))return sum;keys.add(key);return sum+s.width*s.height;},0);
    if(ai.pixels+added>64000000)throw new Error('保持するAI出力が合計6400万画素を超えます。新しい画像を読み込んでキャッシュを消すか、倍率・対象枚数を減らしてください。');
    let failed=0;const errors=[];
    for(let k=0;k<items.length;k++){
      checkCancelled();const {r}=items[k],key=aiKey(r,config);if(ai.cache.has(key))continue;
      try{const result=await workerRun(r,config,p=>{$('aiStatus').textContent=`${k+1} / ${items.length}枚 · ${r.name} · ${p.text}`;$('aiProgress').value=(k+(p.total?(p.done/p.total):0))/items.length;});checkCancelled();ai.cache.set(key,result);ai.pixels+=result.size.width*result.size.height;$('aiProgress').value=(k+1)/items.length;}
      catch(e){if(ai.cancelled||!continueOnError)throw e;failed++;errors.push(`${r.name}: ${e.message}`);}
    }
    $('aiStatus').textContent=failed?`${items.length-failed}枚完了・${failed}枚失敗。${errors.join(' / ')}`:`${items.length}枚のAI拡大が完了しました。比較してから保存してください。`;
    if(failed)message('一部のAI処理に失敗しました。失敗した画像は通常リサイズで代用していません。','error');
  }
  async function showComparison(){
    const token=++ai.compareToken,r=state.rects[state.selected],config=settings(),cached=r&&ai.cache.get(aiKey(r,config));
    $('comparison').hidden=!cached;$('comparisonEmpty').hidden=!!cached;if(!cached)return;
    try{const image=await createImageBitmap(cached.blob);if(token!==ai.compareToken){image.close();return;}
      const original=crop(r),b=C.pixelBox(r,state.width,state.height),s=cached.size;
      const baseline=makeCanvas(s.width,s.height),bg=baseline.getContext('2d');if(config.square){bg.fillStyle='#fffefa';bg.fillRect(0,0,s.width,s.height);}bg.imageSmoothingQuality='high';bg.drawImage(original,(s.width-s.drawWidth)/2,(s.height-s.drawHeight)/2,s.drawWidth,s.drawHeight);
      for(const[id,source]of[['beforeCanvas',baseline],['afterCanvas',image]]){const c=$(id);c.width=s.width;c.height=s.height;c.getContext('2d').drawImage(source,0,0);c.dataset.size=`${s.width}x${s.height}`;}image.close();
      $('beforeSize').textContent=$('afterSize').textContent=`${s.width} × ${s.height}px`;
    }catch(e){if(token===ai.compareToken){$('comparison').hidden=true;$('comparisonEmpty').hidden=false;$('comparisonEmpty').textContent=`比較画像を開けません: ${e.message}`;}}
  }
  async function runAI(all){$('mode').value='ai';updateAIControls();detail();const items=all?state.rects.map((r,i)=>({r:{...r},i})).filter(({r})=>r.enabled):[{r:{...state.rects[state.selected]},i:state.selected}];beginBusy();message('AI拡大を処理しています。停止すると完了済みの画像を保持します。');try{await processAI(items,settings(),all);render();if(!$('aiStatus').textContent.includes('失敗'))message('AI拡大が完了しました。顔や装飾を比較してからPNG / ZIPで保存してください。','success');}finally{endBusy();}}
  bind('clearAI','click',()=>{clearAI();render();message('AI結果を消しました。原画像と切り出し枠は保持しています。');});
  bind('aiOne','click',()=>runAI(false));bind('aiBatch','click',()=>runAI(true));
  $('aiStop').addEventListener('click',()=>{if(!state.busy)return;ai.cancelled=true;if(ai.pending)ai.pending.reject();else{ai.worker?.terminate();ai.worker=null;}$('aiStatus').textContent='停止しました。完了済みのAI画像は保持しています。';});

  bind('export','click',exportZIP);
  function promptView(show){$('editor').hidden=show;$('promptView').hidden=!show;for(const[id,active]of[['tabEditor',!show],['tabPrompt',show]]){$(id).classList.toggle('active',active);$(id).setAttribute('aria-pressed',String(active));}if(!show)draw();}
  bind('tabEditor','click',()=>promptView(false));bind('tabPrompt','click',()=>promptView(true));
  function updatePrompt(){try{const rows=Number($('promptRows').value),cols=Number($('promptCols').value);if(rows*cols>80)throw new Error('最大80マスです。');const text=C.prompt({preset:$('promptPreset').value,rows,cols,size:$('promptSize').value.split('x').map(Number),color:$('promptColor').value,character:$('character').value,labels:$('labels').value});$('promptText').value=text;$('copyPrompt').disabled=false;$('usePrompt').disabled=false;$('promptStatus').className='notice';$('promptStatus').textContent='ChatGPTでキャラクター資料を添付し、このプロンプトを貼り付けてください。';}catch(e){$('promptText').value='';$('copyPrompt').disabled=true;$('usePrompt').disabled=true;$('promptStatus').className='notice error';$('promptStatus').textContent=e.message;}}
  function presetPrompt(){const p=C.PRESETS[$('promptPreset').value];$('promptRows').value=p.rows;$('promptCols').value=p.cols;$('promptSize').value=p.size.join('x');$('labels').value=p.descriptions.join('\n');updatePrompt();}
  bind('promptPreset','change',presetPrompt);for(const id of['promptRows','promptCols','promptSize','promptColor','character','labels'])bind(id,'input',updatePrompt);
  bind('usePrompt','click',()=>{$('preset').value=$('promptPreset').value;$('rows').value=$('promptRows').value;$('cols').value=$('promptCols').value;$('color').value=$('promptColor').value;$('promptStatus').textContent='行数・列数・枠線の色を分割画面に反映しました。生成した画像を読み込んでください。';});
  bind('copyPrompt','click',async()=>{try{await navigator.clipboard.writeText($('promptText').value);$('promptStatus').textContent='プロンプトをコピーしました。ChatGPTに貼り付けて使えます。';}catch{$('promptText').focus();$('promptText').select();if(document.execCommand('copy'))$('promptStatus').textContent='プロンプトをコピーしました。';else $('promptStatus').textContent='コピーが許可されていません。選択済みの文章をCtrl+Cでコピーしてください。';}});
  new ResizeObserver(()=>draw()).observe(stage);$('version').textContent=`v${C.VERSION}`;presetPrompt();updateCounts();
})();
